# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/example.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/example.proto\x12\x07\x65xample\"-\n\x0e\x45xampleRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"?\n\x0f\x45xampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x04user\x18\x02 \x01(\x0b\x32\r.example.User\"!\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x32\x97\x01\n\x0e\x45xampleService\x12@\n\x0bUnaryMethod\x12\x17.example.ExampleRequest\x1a\x18.example.ExampleResponse\x12\x43\n\nBiDiStream\x12\x17.example.ExampleRequest\x1a\x18.example.ExampleResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEREQUEST']._serialized_start=32
  _globals['_EXAMPLEREQUEST']._serialized_end=77
  _globals['_EXAMPLERESPONSE']._serialized_start=79
  _globals['_EXAMPLERESPONSE']._serialized_end=142
  _globals['_USER']._serialized_start=144
  _globals['_USER']._serialized_end=177
  _globals['_EXAMPLESERVICE']._serialized_start=180
  _globals['_EXAMPLESERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
